// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signature.proto

package com.obomprogramador.grpc;

public interface SignResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:signverify.SignResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string signature = 1;</code>
   */
  java.lang.String getSignature();
  /**
   * <code>string signature = 1;</code>
   */
  com.google.protobuf.ByteString
      getSignatureBytes();
}
