# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signature.proto',
  package='signverify',
  syntax='proto3',
  serialized_options=_b('\n\030com.obomprogramador.grpcB\020SignVerifyClientP\001\242\002\003SVC'),
  serialized_pb=_b('\n\x0fsignature.proto\x12\nsignverify\"\x1b\n\x0bSignRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"!\n\x0cSignResponse\x12\x11\n\tsignature\x18\x01 \x01(\t2I\n\nSignVerify\x12;\n\x04Sign\x12\x17.signverify.SignRequest\x1a\x18.signverify.SignResponse\"\x00\x42\x34\n\x18\x63om.obomprogramador.grpcB\x10SignVerifyClientP\x01\xa2\x02\x03SVCb\x06proto3')
)




_SIGNREQUEST = _descriptor.Descriptor(
  name='SignRequest',
  full_name='signverify.SignRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='signverify.SignRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=58,
)


_SIGNRESPONSE = _descriptor.Descriptor(
  name='SignResponse',
  full_name='signverify.SignResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='signverify.SignResponse.signature', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['SignRequest'] = _SIGNREQUEST
DESCRIPTOR.message_types_by_name['SignResponse'] = _SIGNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignRequest = _reflection.GeneratedProtocolMessageType('SignRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNREQUEST,
  '__module__' : 'signature_pb2'
  # @@protoc_insertion_point(class_scope:signverify.SignRequest)
  })
_sym_db.RegisterMessage(SignRequest)

SignResponse = _reflection.GeneratedProtocolMessageType('SignResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNRESPONSE,
  '__module__' : 'signature_pb2'
  # @@protoc_insertion_point(class_scope:signverify.SignResponse)
  })
_sym_db.RegisterMessage(SignResponse)


DESCRIPTOR._options = None

_SIGNVERIFY = _descriptor.ServiceDescriptor(
  name='SignVerify',
  full_name='signverify.SignVerify',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=95,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sign',
    full_name='signverify.SignVerify.Sign',
    index=0,
    containing_service=None,
    input_type=_SIGNREQUEST,
    output_type=_SIGNRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIGNVERIFY)

DESCRIPTOR.services_by_name['SignVerify'] = _SIGNVERIFY

# @@protoc_insertion_point(module_scope)
